#include "Common.h"

namespace DYNAMIC_XAML_NAMESPACE_MIDL
{
    static runtimeclass XamlMetadataProviderHelper
    {
        [static_name("IXamlMetadataProviderHelperStatics", 598305E3-6E01-426D-84BF-6E019CFB45E0)]
        {
            [default_overload]
            static Windows.Foundation.IAsyncOperation<IVectorView<String> > GetProviderTypeNamesFromAssemblyAsync(String assemblyPath);
            [method_name("GetProviderTypeNamesFromAssemblyAsyncWithBytes")]
            static Windows.Foundation.IAsyncOperation<IVectorView<String> > GetProviderTypeNamesFromAssemblyAsync(UInt8[] assemblyBytes);
            [method_name("GetProviderTypeNamesFromAssemblyAsyncWithStream")]
                static Windows.Foundation.IAsyncOperation<IVectorView<String> > GetProviderTypeNamesFromAssemblyAsync(Windows.Storage.Streams.IRandomAccessStream assemblyStream);
            [method_name("GetProviderTypeNamesFromAssemblyAsyncWithStorageFile")]
            static Windows.Foundation.IAsyncOperation<IVectorView<String> > GetProviderTypeNamesFromAssemblyAsync(Windows.Storage.StorageFile assemblyFile);
        }
    };
}